-- CON ESTE SCRIPT SE PUEDE CREAR LA BD A PARTIR DEL ESQUEMA. ES FORWARD ENGINEER 

-- MySQL Script generated by MySQL Workbench
-- Mon Jun 20 20:46:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blockbuster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blockbuster` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

USE `Blockbuster` ;

-- -----------------------------------------------------
-- Table `Blockbuster`.`t_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`t_actor` (
  `actor_id` INT NOT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Blockbuster`.`t_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`t_category` (
  `category_id` INT NOT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Blockbuster`.`t_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`t_inventory` (
  `film_id` INT NOT NULL,
  `inventory_id` VARCHAR(100) NULL DEFAULT NULL,
  `store_id` VARCHAR(1000) NULL DEFAULT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`film_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Blockbuster`.`t_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`t_language` (
  `language_id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Blockbuster`.`t_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`t_film` (
  `film_id` INT NOT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` INT NULL DEFAULT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `rental_duration` INT NULL DEFAULT NULL,
  `rental_rate` DOUBLE NULL DEFAULT NULL,
  `length` INT NULL DEFAULT NULL,
  `replacement_cost` DOUBLE NULL DEFAULT NULL,
  `rating` TEXT NULL DEFAULT NULL,
  `special_features` TEXT NULL DEFAULT NULL,
  `last_update` TEXT NULL DEFAULT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`film_id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `language_id_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `Blockbuster`.`t_inventory` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `Blockbuster`.`t_language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `Blockbuster`.`t_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Blockbuster`.`t_rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`t_rental` (
  `rental_id` INT NOT NULL,
  `rental_date` DATE NULL DEFAULT NULL,
  `inventory_id` VARCHAR(1000) NULL DEFAULT NULL,
  `last_update` DATE NULL DEFAULT NULL,
  `customer_id` VARCHAR(100) NULL DEFAULT NULL,
  `return_date` DATE NULL DEFAULT NULL,
  `staff_id` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`rental_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Blockbuster`.`actorsxfilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blockbuster`.`actorsxfilms` (
  `actors_id` INT,
  `film_id` INT,
  PRIMARY KEY (`film_id`, `actors_id`),
  INDEX `actors_id_idx` (`actors_id` ASC) VISIBLE,
    FOREIGN KEY (`actors_id`)
    REFERENCES `Blockbuster`.`t_actor` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`film_id`)
    REFERENCES `Blockbuster`.`t_film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
